name: SpawnCommand
version: 1.1
api: 3.0.0-ALPHA11
author: WortTuner
main: SpawnCommand\Main

commands:
  spawn:
    description: "Teleport to spawn"
    usage: "/spawn"
    permission: "spawncommand.command.spawn"

permissions:
  spawn:
    default: true
    description: "Allows player to go to spawn point"

